name       : oxygen
version    : 5.11.3
release    : 2
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.3/oxygen-5.11.3.tar.xz : d76b3f5ce15808805a1b6762c01bf103ded56caf14a80750324d851b6dc3e37d
license    :
    - GPL-2.0
    - LGPL-2.1
component  :
    - desktop.theme
    - sound-theme : desktop.kde.core
summary    :
    - Oxygen visual style for the Plasma desktop
    - sound-theme : System sounds for the Plasma desktop
description:
    - Oxygen visual style for the Plasma desktop.
    - sound-theme : System sounds for the Plasma desktop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
    - frameworkintegration-devel
    - kcompletion-devel
    - kconfig-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kservice-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
patterns   :
    - devel : /usr/bin/oxygen-demo5
    - sound-theme : /usr/share/sounds
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
