name       : oxygen
version    : 5.22.5
release    : 63
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.5/oxygen-5.22.5.tar.xz : 0c3bb29ce140b00e1c95a0a1cb39c662d935f7216e61810837097a39516ec43b
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  :
    - desktop.theme
    - sound-theme : desktop.kde.core
summary    :
    - Oxygen visual style for the Plasma desktop
    - sound-theme : System sounds for the Plasma desktop
description:
    - Oxygen visual style for the Plasma desktop.
    - sound-theme : System sounds for the Plasma desktop.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - frameworkintegration-devel
    - kcmutils-devel
    - kcompletion-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kservice-devel
    - kwayland-devel
    - kwindowsystem-devel
rundeps    :
    - sound-theme : sound-theme-freedesktop
patterns   :
    - devel : /usr/bin/oxygen-demo5
    - sound-theme : /usr/share/sounds
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
