name       : oxygen
version    : 5.22.1
release    : 60
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.1/oxygen-5.22.1.tar.xz : 8c60030ee43f3a3c61aa1e53d55b06c6bf2fee3da61403c2df3a18b5a0137a69
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  :
    - desktop.theme
    - sound-theme : desktop.kde.core
summary    :
    - Oxygen visual style for the Plasma desktop
    - sound-theme : System sounds for the Plasma desktop
description:
    - Oxygen visual style for the Plasma desktop.
    - sound-theme : System sounds for the Plasma desktop.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - frameworkintegration-devel
    - kcmutils-devel
    - kcompletion-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kservice-devel
    - kwayland-devel
    - kwindowsystem-devel
patterns   :
    - devel : /usr/bin/oxygen-demo5
    - sound-theme : /usr/share/sounds
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
