name       : oxygen
version    : 5.10.5
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.10.5/oxygen-5.10.5.tar.xz : a97a01d0db02b4b1574f5652a9ff1ffef84b085ed67c2b8f68b3818d56d6315c
license    :
    - GPL-2.0
    - LGPL-2.1
component  :
    - desktop.theme
    - sound-theme : desktop.kde.core
summary    :
    - Oxygen visual style for the Plasma desktop
    - sound-theme : System sounds for the Plasma desktop
description:
    - Oxygen visual style for the Plasma desktop.
    - sound-theme : System sounds for the Plasma desktop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
    - frameworkintegration-devel
    - kcompletion-devel
    - kconfig-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kservice-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
patterns   :
    - devel : /usr/bin/oxygen-demo5
    - sound-theme : /usr/share/sounds
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
