name       : oxygen
version    : 5.17.5
release    : 38
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.5/oxygen-5.17.5.tar.xz : 58954374a4b9067365ee5d50b32b1986b2e7dd31e73cbf79fda8d978949943be
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  :
    - desktop.theme
    - sound-theme : desktop.kde.core
optimize   : lto
summary    :
    - Oxygen visual style for the Plasma desktop
    - sound-theme : System sounds for the Plasma desktop
description:
    - Oxygen visual style for the Plasma desktop.
    - sound-theme : System sounds for the Plasma desktop.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
    - frameworkintegration-devel
    - kcmutils-devel
    - kcompletion-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kservice-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
patterns   :
    - devel : /usr/bin/oxygen-demo5
    - sound-theme : /usr/share/sounds
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
