name       : oxygen
version    : 5.23.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.0/oxygen-5.23.0.tar.xz : 6c04ed2e5eca4d0dd82034875cd159dfd149ca412032258055f6a848ecbfe09e
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  :
    - desktop.theme
    - sound-theme : desktop.kde.core
summary    :
    - Oxygen visual style for the Plasma desktop
    - sound-theme : System sounds for the Plasma desktop
description:
    - Oxygen visual style for the Plasma desktop.
    - sound-theme : System sounds for the Plasma desktop.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - frameworkintegration-devel
    - kcmutils-devel
    - kcompletion-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kservice-devel
    - kwayland-devel
    - kwindowsystem-devel
rundeps    :
    - sound-theme : sound-theme-freedesktop
patterns   :
    - devel : /usr/bin/oxygen-demo5
    - sound-theme : /usr/share/sounds
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
