name       : oxygen
version    : 5.16.4
release    : 32
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.4/oxygen-5.16.4.tar.xz : 7ba8a18a0b44d2bf48c96679328f698a9bfd4d041724b960095fed67f228f2e1
license    :
    - GPL-2.0
    - LGPL-2.1
component  :
    - desktop.theme
    - sound-theme : desktop.kde.core
optimize   : lto
summary    :
    - Oxygen visual style for the Plasma desktop
    - sound-theme : System sounds for the Plasma desktop
description:
    - Oxygen visual style for the Plasma desktop.
    - sound-theme : System sounds for the Plasma desktop.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
    - frameworkintegration-devel
    - kcmutils-devel
    - kcompletion-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kservice-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
patterns   :
    - devel : /usr/bin/oxygen-demo5
    - sound-theme : /usr/share/sounds
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
